title: vulphix
domain: doc.vulphix.com # (optional)
description: this is the docs of your vulphix
handle: https://x.com/codeshaine
source: src
build: dist
sidebar:
  - title: Basics
    pages:
      - - Installation
        - /basics/installation
      - - Usage
        - /basics/usage
      - - Config File
        - /basics/configfile
  - title: Guides
    pages:
      - - Deployement
        - /guides/deploy
  - title: Links
    pages:
      - - Github
        - https://github.com/codeshaine/vulphix
      - - Twitter
        - https://x.com/code_shaine
